//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.inches_convert")]
    public interface inches_convert {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/inches_convert/inches_toYards", ReplyAction="http://tempuri.org/inches_convert/inches_toYardsResponse")]
        float inches_toYards(int a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/inches_convert/inches_toYards", ReplyAction="http://tempuri.org/inches_convert/inches_toYardsResponse")]
        System.Threading.Tasks.Task<float> inches_toYardsAsync(int a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/inches_convert/inches_toFeet", ReplyAction="http://tempuri.org/inches_convert/inches_toFeetResponse")]
        float inches_toFeet(int a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/inches_convert/inches_toFeet", ReplyAction="http://tempuri.org/inches_convert/inches_toFeetResponse")]
        System.Threading.Tasks.Task<float> inches_toFeetAsync(int a);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface inches_convertChannel : WindowsFormsApp1.ServiceReference1.inches_convert, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class inches_convertClient : System.ServiceModel.ClientBase<WindowsFormsApp1.ServiceReference1.inches_convert>, WindowsFormsApp1.ServiceReference1.inches_convert {
        
        public inches_convertClient() {
        }
        
        public inches_convertClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public inches_convertClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public inches_convertClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public inches_convertClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public float inches_toYards(int a) {
            return base.Channel.inches_toYards(a);
        }
        
        public System.Threading.Tasks.Task<float> inches_toYardsAsync(int a) {
            return base.Channel.inches_toYardsAsync(a);
        }
        
        public float inches_toFeet(int a) {
            return base.Channel.inches_toFeet(a);
        }
        
        public System.Threading.Tasks.Task<float> inches_toFeetAsync(int a) {
            return base.Channel.inches_toFeetAsync(a);
        }
    }
}
